-- 12개
DELETE FROM TB_BSK;
DELETE FROM TB_BBS;
DELETE FROM TB_BUY_DTL;
DELETE FROM TB_BUY_MST;
DELETE FROM TB_PAY;
DELETE FROM TB_SLE_IMG;
DELETE FROM TB_SLE;
DELETE FROM TB_PRD;
DELETE FROM TB_TRM_AGR;
DELETE FROM TB_STAT_MBR;
DELETE FROM TB_MBR_DTL;
DELETE FROM TB_MBR_MST;
DELETE FROM TB_SLL;
DELETE FROM TB_MNG;
COMMIT;

/*
DROP INDEX IDX_TB_MBR_LOGIN;
ALTER TABLE TB_MBR_MST DROP CONSTRAINT UK1_TB_MBR;

DROP TABLE TB_BSK;
DROP TABLE TB_BBS;
DROP TABLE TB_BUY_DTL;
DROP TABLE TB_BUY_MST;
DROP TABLE TB_PAY;
DROP TABLE TB_SLE_IMG;
DROP TABLE TB_SLE;
DROP TABLE TB_PRD;
DROP TABLE TB_TRM_AGR;
DROP TABLE TB_STAT_MBR;
DROP TABLE TB_MBR_DTL;
DROP TABLE TB_MBR_MST;
DROP TABLE TB_SLL;
DROP TABLE TB_MNG;

DROP SEQUENCE SQ_SEQ_BSK;
DROP SEQUENCE SQ_SEQ_BBS;
DROP SEQUENCE SQ_SEQ_MBR;
DROP SEQUENCE SQ_SEQ_SLL;
DROP SEQUENCE SQ_SEQ_MNG;
DROP SEQUENCE SQ_SEQ_PRD;
DROP SEQUENCE SQ_SEQ_SLE;
DROP SEQUENCE SQ_SEQ_BUY_MST;
DROP SEQUENCE SQ_SEQ_BUY_DTL;
DROP SEQUENCE SQ_SEQ_PAY;
DROP SEQUENCE SQ_SEQ_TRM_AGR;
DROP SEQUENCE SQ_SEQ_SLE_IMG;
*/

-- 휴지통 비우기
-- purge recyclebin;